In [1]:
from google.colab import files
uploaded=files.upload()

Saving Train.csv to Train.csv


In [2]:
import numpy as np
import pandas as pd
dataset=pd.read_csv('Train.csv')

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split

y = dataset.Item_Outlet_Sales
X = dataset.drop(['Item_Outlet_Sales'], axis=1).select_dtypes(exclude=['object'])

In [7]:
#Splitting The data  into Train and Test Dataset:
from sklearn.model_selection import train_test_split
#Independent Variables:
x = dataset.drop("Item_Outlet_Sales", axis = 1) 

#Depenedent Variables 
y = dataset["Item_Outlet_Sales"].values.reshape(-1,1)
x_train,x_test, y_train, y_test = train_test_split(x,y, test_size =0.20, random_state = 3)

In [15]:
from sklearn import preprocessing
# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
# Encode labels in column 'species'.
dataset['Outlet_Identifier']= label_encoder.fit_transform(dataset['Outlet_Identifier'])
dataset['Outlet_Identifier'].unique()

array([9, 3, 0, 1, 5, 7, 2, 8, 6, 4])

In [14]:
from sklearn import preprocessing
# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
# Encode labels in column 'species'.
dataset['Item_Identifier']= label_encoder.fit_transform(dataset['Item_Identifier'])
dataset['Item_Identifier'].unique()

array([ 156,    8,  662, ..., 1323, 1524, 1519])

In [13]:
from sklearn import preprocessing
# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
# Encode labels in column 'species'.
dataset['Item_Fat_Content']= label_encoder.fit_transform(dataset['Item_Fat_Content'])
dataset['Item_Fat_Content'].unique()

array([1, 2, 3, 0, 4])

In [12]:
from sklearn import preprocessing
# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
# Encode labels in column 'species'.
dataset['Item_Type']= label_encoder.fit_transform(dataset['Item_Type'])
dataset['Item_Type'].unique()

array([ 4, 14, 10,  6,  9,  0, 13,  5,  2,  8,  7,  3,  1, 15, 11, 12])

In [11]:
from sklearn import preprocessing
# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
# Encode labels in column 'species'.
dataset['Outlet_Size']= label_encoder.fit_transform(dataset['Outlet_Size'])
dataset['Outlet_Size'].unique()

array([1, 3, 0, 2])

In [10]:
from sklearn import preprocessing
# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
# Encode labels in column 'species'.
dataset['Outlet_Location_Type']= label_encoder.fit_transform(dataset['Outlet_Location_Type'])
dataset['Outlet_Location_Type'].unique()

array([0, 2, 1])

In [9]:
from sklearn import preprocessing
# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
# Encode labels in column 'species'.
dataset['Outlet_Type']= label_encoder.fit_transform(dataset['Outlet_Type'])
dataset['Outlet_Type'].unique()

array([1, 2, 0, 3])

In [ ]:
label_encoder = preprocessing.LabelEncoder()
# Encode labels in column 'species'.
dataset['Outlet_Identifier']= label_encoder.fit_transform(dataset['Outlet_Identifier'])
dataset['Outlet_Identifier'].unique()

dataset['Item_Identifier']= label_encoder.fit_transform(dataset['Item_Identifier'])
dataset['Item_Identifier'].unique()



In [16]:
from xgboost import XGBRegressor

my_model = XGBRegressor()
# Add silent=True to avoid printing out updates with each cycle
my_model.fit(x_train, y_train, verbose=False)

ValueError: ignored